version: '3.8'
services:
  proxy_43:
    container_name: mbr_proxy_43
    image: massbit/massbitroute_test_proxy:v0.1.0
    restart: always
    networks:
      mbr_test_network_43:
        ipv4_address: "172.24.43.254"
    environment:
      - DATASOURCE=http:\/\/34.81.232.186:8545
      - DATASOURCE_WS=ws:\/\/34.81.232.186:8546
      - DOMAIN=massbitroute.net
      - NETWORK_NUMBER=43
      - TEST_MODE=test
    volumes:
      - ./proxy/logs:/logs
      - ./proxy/vars:/vars
      - ./proxy/reports:/reports
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      #- ./proxy/resolv.conf:/etc/resolv.conf
      - /home/massbit/massbit/massbitroute_test/end2end/test:/test
      #- /etc/letsencrypt:/etc/letsencrypt
    extra_hosts:
      - "hostmaster.massbitroute.net:172.24.43.2"
      - "ns1.massbitroute.net:172.24.43.2"
      - "ns2.massbitroute.net:172.24.43.2"
      - "api.massbitroute.net:172.24.43.6"
      - "session.mbr.massbitroute.net:172.24.43.7"
      - "chain.massbitroute.net:172.24.43.20"
      - "portal.massbitroute.net:172.24.43.10"
      - "admin-api.massbitroute.net:172.24.43.11"
      - "dapi.massbitroute.net:172.24.43.11"
      - "scheduler.fisherman.massbitroute.net:172.24.43.15"
      - "api.ipapi.com:172.24.43.254"
      - "staking.massbitroute.net:172.24.43.12"
      - "git.massbitroute.net:172.24.43.5"

  db_43:
    container_name: mbr_db_43
    image: postgres:14.4-alpine
    restart: always
    networks:
      mbr_test_network_43:
        ipv4_address: "172.24.43.13"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_USER=postgres
      - APP_DB_PASS=postgres
      - APP_DB_NAME=massbit-user
      - FISHERMAN_DB_NAME=massbit-fisherman
      # ports:
      # - '5432:5432'
    volumes:
      # - db-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    extra_hosts:
      - "hostmaster.massbitroute.net:172.24.43.254"
      - "ns1.massbitroute.net:172.24.43.254"
      - "ns2.massbitroute.net:172.24.43.254"
      - "api.massbitroute.net:172.24.43.254"
      - "stat.mbr.massbitroute.net:172.24.43.254"
      - "monitor.mbr.massbitroute.net:172.24.43.254"
      - "chain.massbitroute.net:172.24.43.20"
      - "portal.massbitroute.net:172.24.43.254"
      - "admin-api.massbitroute.net:172.24.43.254"
      - "dapi.massbitroute.net:172.24.43.254"
      - "scheduler.fisherman.massbitroute.net:172.24.43.254"
      - "gateway-dot-mainnet.monitor.mbr.massbitroute.net:172.24.43.254"
      - "gateway-eth-mainnet.monitor.mbr.massbitroute.net:172.24.43.254"
      - "node-eth-mainnet.monitor.mbr.massbitroute.net:172.24.43.254"
      - "node-dot-mainnet.monitor.mbr.massbitroute.net:172.24.43.254"
      - "node-eth-mainnet.stat.mbr.massbitroute.net:172.24.43.254"
      - "node-dot-mainnet.stat.mbr.massbitroute.net:172.24.43.254"
      - "gateway-eth-mainnet.stat.mbr.massbitroute.net:172.24.43.254"
      - "gateway-dot-mainnet.stat.mbr.massbitroute.net:172.24.43.254"
      - "api.ipapi.com:172.24.43.254"
      - "staking.massbitroute.net:172.24.43.254"

  redis_43:
    container_name: mbr_redis_43
    image: redis:7.0.2-alpine
    restart: always
    networks:
      mbr_test_network_43:
        ipv4_address: "172.24.43.14"
    #ports:
    #  - '6379:6379'
    volumes:
      - redis-data:/data
    extra_hosts:
      - "hostmaster.massbitroute.net:172.24.43.254"
      - "ns1.massbitroute.net:172.24.43.254"
      - "ns2.massbitroute.net:172.24.43.254"
      - "api.massbitroute.net:172.24.43.254"
      - "stat.mbr.massbitroute.net:172.24.43.254"
      - "monitor.mbr.massbitroute.net:172.24.43.254"
      - "chain.massbitroute.net:172.24.43.20"
      - "portal.massbitroute.net:172.24.43.254"
      - "admin-api.massbitroute.net:172.24.43.254"
      - "dapi.massbitroute.net:172.24.43.254"
      - "scheduler.fisherman.massbitroute.net:172.24.43.254"
      - "gateway-dot-mainnet.monitor.mbr.massbitroute.net:172.24.43.254"
      - "gateway-eth-mainnet.monitor.mbr.massbitroute.net:172.24.43.254"
      - "node-eth-mainnet.monitor.mbr.massbitroute.net:172.24.43.254"
      - "node-dot-mainnet.monitor.mbr.massbitroute.net:172.24.43.254"
      - "node-eth-mainnet.stat.mbr.massbitroute.net:172.24.43.254"
      - "node-dot-mainnet.stat.mbr.massbitroute.net:172.24.43.254"
      - "gateway-eth-mainnet.stat.mbr.massbitroute.net:172.24.43.254"
      - "gateway-dot-mainnet.stat.mbr.massbitroute.net:172.24.43.254"
      - "api.ipapi.com:172.24.43.254"
      - "staking.massbitroute.net:172.24.43.254"

  massbitchain_43:
    container_name: mbr_chain_43
    image: massbit/massbitroute_chain:w3f-milestone-2
    # build: ../massbitchain
    restart: always
    networks:
      mbr_test_network_43:
        ipv4_address: "172.24.43.20"
    ports:
      - '6043:9944'

  api_43:
    privileged: true
    restart: unless-stopped
    networks:
      mbr_test_network_43:
        ipv4_address: "172.24.43.6"

    image: massbit/massbitroute_api:v0.1.15
    # command: sed -i "s|export WHITELIST_PARTNERS=.*|export WHITELIST_PARTNERS=\"allow 172.24.43.10\"|g" /massbit/massbitroute/app/src/sites/services/api/env/api.env
    command: "-n"
    # build:
    #   context: /massbit/massbitroute/app/src/sites/services/api
    #   dockerfile: install/mbr/build/api/Dockerfile.dev
    #   args:
    #     VERSION: 0.0.1-shamu-dev
    #     BRANCH: shamu
    container_name: mbr_api_43
    # network_mode: "host"
    # ports:
    #   - "443:443"
    volumes:
      - ./api/logs:/massbit/massbitroute/app/src/sites/services/api/logs:rw
      - ./api/vars:/massbit/massbitroute/app/src/sites/services/api/vars:rw
      # - ./api/tmp:/massbit/massbitroute/app/src/sites/services/api/tmp:rw
      - ./api/db:/massbit/massbitroute/app/src/sites/services/api/db:rw
    environment:
      - MBR_ENV=v0.1.15
      - MKAGENT_BRANCH=shamu
      - GIT_PRIVATE_BRANCH=shamu
      - GIT_PRIVATE_READ_URL=http://massbit:REN4jRRO0G1BEsU8v3qyTnpShMzQc3ml@git.massbitroute.net
    extra_hosts:
      - "hostmaster.massbitroute.net:172.24.43.254"
      - "ns1.massbitroute.net:172.24.43.254"
      - "ns2.massbitroute.net:172.24.43.254"
      - "api.massbitroute.net:172.24.43.254"
      - "stat.mbr.massbitroute.net:172.24.43.254"
      - "monitor.mbr.massbitroute.net:172.24.43.254"
      - "chain.massbitroute.net:172.24.43.20"
      - "portal.massbitroute.net:172.24.43.254"
      - "admin-api.massbitroute.net:172.24.43.254"
      - "dapi.massbitroute.net:172.24.43.254"
      - "scheduler.fisherman.massbitroute.net:172.24.43.254"
      - "gateway-dot-mainnet.monitor.mbr.massbitroute.net:172.24.43.254"
      - "gateway-eth-mainnet.monitor.mbr.massbitroute.net:172.24.43.254"
      - "node-eth-mainnet.monitor.mbr.massbitroute.net:172.24.43.254"
      - "node-dot-mainnet.monitor.mbr.massbitroute.net:172.24.43.254"
      - "node-eth-mainnet.stat.mbr.massbitroute.net:172.24.43.254"
      - "node-dot-mainnet.stat.mbr.massbitroute.net:172.24.43.254"
      - "gateway-eth-mainnet.stat.mbr.massbitroute.net:172.24.43.254"
      - "gateway-dot-mainnet.stat.mbr.massbitroute.net:172.24.43.254"
      - "api.ipapi.com:172.24.43.254"
      - "staking.massbitroute.net:172.24.43.254"
      - "git.massbitroute.net:172.24.43.5"

  session_43:
    privileged: true
    restart: unless-stopped
    networks:
      mbr_test_network_43:
        ipv4_address: "172.24.43.7"

    image: massbit/massbitroute_session:v0.1.0
    command: "-n"
    container_name: mbr_session_43
    # network_mode: "host"
    # ports:
    #   - "443:443"
    volumes:
      - ./session/logs:/massbit/massbitroute/app/src/sites/services/session/logs:rw
      - ./session/vars:/massbit/massbitroute/app/src/sites/services/session/vars:rw
      - ./session/db:/massbit/massbitroute/app/src/sites/services/session/db:rw
    environment:
      - MBR_ENV=v0.1.0
      - MKAGENT_BRANCH=shamu
      - GIT_PRIVATE_BRANCH=shamu
      - GIT_PRIVATE_READ_URL=http://massbit:REN4jRRO0G1BEsU8v3qyTnpShMzQc3ml@git.massbitroute.net


  gwman_43:
    privileged: true
    networks:
      mbr_test_network_43:
        ipv4_address: "172.24.43.2"

    restart: unless-stopped
    image: massbit/massbitroute_gwman:v0.1.8
    command: "-n"
    # build:
    #   context: /massbit/massbitroute/app/src/sites/services/gwman
    #   dockerfile: install/mbr/build/gwman/Dockerfile.dev
    #   args:
    #     VERSION: 0.0.1-shamu-dev
    #     BRANCH: shamu
    container_name: mbr_gwman_43
    volumes:
      - ./gwman/logs:/massbit/massbitroute/app/src/sites/services/gwman/logs:rw
      - ./gwman/vars:/massbit/massbitroute/app/src/sites/services/gwman/vars:rw
      - ./gwman/db:/massbit/massbitroute/app/src/sites/services/gwman/db:rw
    environment:
      - GIT_PUBLIC_URL="https://github.com"
      - MBR_ENV=v0.1.8
      - MKAGENT_BRANCH=shamu
      - GIT_PRIVATE_BRANCH=shamu
      - GIT_PRIVATE_READ_URL=http://massbit:REN4jRRO0G1BEsU8v3qyTnpShMzQc3ml@git.massbitroute.net

    extra_hosts:
      - "hostmaster.massbitroute.net:172.24.43.254"
      - "ns1.massbitroute.net:172.24.43.254"
      - "ns2.massbitroute.net:172.24.43.254"
      - "api.massbitroute.net:172.24.43.254"
      - "stat.mbr.massbitroute.net:172.24.43.254"
      - "monitor.mbr.massbitroute.net:172.24.43.254"
      - "chain.massbitroute.net:172.24.43.20"
      - "portal.massbitroute.net:172.24.43.254"
      - "admin-api.massbitroute.net:172.24.43.254"
      - "dapi.massbitroute.net:172.24.43.254"
      - "scheduler.fisherman.massbitroute.net:172.24.43.254"
      - "api.ipapi.com:172.24.43.254"
      - "staking.massbitroute.net:172.24.43.254"
      - "git.massbitroute.net:172.24.43.5"

volumes:
  db-data:
    driver: local
  redis-data:
    driver: local


#  docker network create -d bridge --gateway 172.24.43.1 --subnet 172.24.43.0/24   mbr_test_network_43
