version: '3.8'
networks:
  mbr_test_network_43:
    driver: bridge
    external: true
    # ipam:
      # config:
      #     - subnet: "172.24.43.0/16"
services:
  git_43:
    privileged: true
    networks:
      mbr_test_network_43:
        ipv4_address: "172.24.43.5"

    restart: unless-stopped
    image: massbit/massbitroute_git:v0.1.13
    command: "-n"
    # build:
    #   context: /massbit/massbitroute/app/src/sites/services/git
    #   dockerfile: install/mbr/build/git/Dockerfile.dev
    #   args:
    #     VERSION: 0.0.1-shamu-dev
    #     BRANCH: shamu
    container_name: mbr_git_43
    volumes:
      - ./git/deploy:/massbit/massbitroute/app/src/sites/services/git/deploy:rw
      - ./git/logs:/massbit/massbitroute/app/src/sites/services/git/logs:rw
      - ./git/vars:/massbit/massbitroute/app/src/sites/services/git/vars:rw
      - ./git/data:/massbit/massbitroute/app/src/sites/services/git/data:rw
      # - ./git/tmp:/massbit/massbitroute/app/src/sites/services/git/tmp:rw
      - ./git/db:/massbit/massbitroute/app/src/sites/services/git/db:rw
    environment:
      - GIT_PUBLIC_URL="https://github.com"
      - MBR_ENV=v0.1.13
      - DOMAIN=massbitroute.net
      - MKAGENT_BRANCH=shamu
      - GIT_PRIVATE_BRANCH=shamu
      - STAT_PROMETHEUS_SCHEME=http
    extra_hosts:
      - "hostmaster.massbitroute.net:172.24.43.254"
      - "ns1.massbitroute.net:172.24.43.254"
      - "ns2.massbitroute.net:172.24.43.254"
      - "api.massbitroute.net:172.24.43.254"
      - "stat.mbr.massbitroute.net:172.24.43.254"
      - "monitor.mbr.massbitroute.net:172.24.43.254"
      - "chain.massbitroute.net:172.24.43.20"
      - "portal.massbitroute.net:172.24.43.254"
      - "admin-api.massbitroute.net:172.24.43.254"
      - "dapi.massbitroute.net:172.24.43.254"
      - "scheduler.fisherman.massbitroute.net:172.24.43.254"
      - "api.ipapi.com:172.24.43.254"
      - "staking.massbitroute.net:172.24.43.254"
      - "git.massbitroute.net:172.24.43.5"

volumes:
  db-data:
    driver: local
  redis-data:
    driver: local


#  docker network create -d bridge --gateway 172.24.43.1 --subnet 172.24.43.0/24   mbr_test_network_43
